### ISSUE TITLE
bug: renamed aws.* setting in Karpenter 0.32

### ISSUE THREAD

**Issue by petrzjunior** [lablabs/terraform-aws-eks-karpenter#9]
### Summary

Karpenter Helm chart changed variable names from `settings.aws.*` to `settings.*` in 0.32.
The renaming scheme in written in the docs: https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#helm-values
Reference: https://github.com/aws/karpenter-provider-aws/issues/5366

### Issue Type

Bug Report

### Terraform Version

```console
Terraform v1.7.4
on linux_amd64
```

### Steps to Reproduce

Install the modue with Karpenter version >= 0.32.

### Expected Results

I expect the module to fill e.g.  `settings.clusterName` as the Helm chart expects.

### Actual Results

Instead `settings.aws.clusterName` is used which is not used by the Helm chart. Karpenter console output:

```console
panic: validating options, missing field, cluster-name
```

**Comment by dojci** [comment]
Thx for reporting, this will be fixed in the upcoming release https://github.com/lablabs/terraform-aws-eks-karpenter/pull/11

**Comment by jaygridley** [comment]
Fixed by https://github.com/lablabs/terraform-aws-eks-karpenter/releases/tag/v2.0.0
